name: social-network-backend
schema: schema.api.graphql
authenticationType: AMAZON_COGNITO_USER_POOLS
userPoolConfig:
  awsRegion: 'us-east-2'
  defaultAction: ALLOW
  userPoolId: !Ref UserPool
mappingTemplatesLocation: mapping-templates
mappingTemplates: 
  - type: Query
    field: getMyProfile
    dataSource: usersTable
  
  - type: Query
    field: getImageUploadUrl
    dataSource: getImageUploadUrlFunction
    request: false
    response: false
  
  - type: Query
    field: getTweets
    dataSource: tweetsTable

  - type: Query
    field: getMyTimeline
    dataSource: timelinesTable

  - type: Query
    field: getLikes
    dataSource: likesTable
  
  - type: Mutation
    field: editMyProfile
    dataSource: usersTable
  
  - type: Mutation
    field: tweet
    dataSource: tweetFunction
    request: false
    response: false

  - type: Mutation
    field: like
    dataSource: likesTimeline
  
  - type: Mutation
    field: unlike
    dataSource: unLikesTable
  
  #nested fields
  - type: Tweet
    field: profile
    dataSource: usersTable
  - type: Tweet
    field: liked
    dataSource: likesTable
  - type: UnHydratedTweetsPage
    field: tweets
    dataSource: tweetsTable


dataSources:
  - type: NONE
    name: none
  - type: AMAZON_DYNAMODB
    name: usersTable
    config: 
      tableName: !Ref UsersTable
  - type: AMAZON_DYNAMODB
    name: tweetsTable
    config:
      tableName: !Ref TweetsTable
  - type: AMAZON_DYNAMODB
    name: timelinesTable
    config:
      tableName: !Ref TimelineTable
  
  - type: AMAZON_DYNAMODB
    name: likesTimeline
    config:
      tableName: !Ref LikesTable
      iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:UpdateItem
        Resource:
          - !GetAtt UsersTable.Arn
          - !GetAtt TweetsTable.Arn
      - Effect: Allow
        Action: dynamodb:PutItem
        Resource: !GetAtt LikesTable.Arn

  - type: AMAZON_DYNAMODB
    name: likesTable
    config:
      tableName: !Ref LikesTable
  
  - type: AMAZON_DYNAMODB
    name: unLikesTable
    config:
      tableName: !Ref LikesTable
      iamRoleStatements:
      - Effect: Allow
        Action: dynamodb:UpdateItem
        Resource:
          - !GetAtt UsersTable.Arn
          - !GetAtt TweetsTable.Arn
      - Effect: Allow
        Action: dynamodb:DeleteItem
        Resource: !GetAtt LikesTable.Arn
    
  - type: AWS_LAMBDA
    name: getImageUploadUrlFunction
    config:
      functionName: getImageUploadUrlFunction
  - type: AWS_LAMBDA
    name: tweetFunction
    config:
      functionName: tweet

substitutions:
  TweetsTable: !Ref TweetsTable
  LikesTable: !Ref LikesTable
  UsersTable: !Ref UsersTable